hostname: ubuntu
manage_etc_hosts: true

users:
  - name: jay
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBVDT6WstypEl+66g71mLfLQhL8uyG9cEQKJ6MypJjtt jay@getlantern.org

packages:
  - curl
  - vim
  - git
  - python3
  - iproute2
  - iw
  - iputils-ping
  - wireguard

runcmd:
  - apt-get update
  - apt-get upgrade -y
  - echo "Cloud-init setup $(date) complete!" > /etc/motd
